In [1]:
import numpy as np

### Functions

In [2]:
def complete_sequence(child, parent, cx_point, d):
    idx_child = idx_parent = cx_point[1]
    not_complete = True
    # complete upper range of the sequence first
    while not_complete:
    # for idx in range(cx_point[1], dim):
        if parent[idx_parent] not in child:
            child[idx_child] = parent[idx_parent]
            if idx_child == (d-1):
                idx_child = 0
            else:
                idx_child = idx_child + 1
        if idx_parent == (d-1):
            idx_parent = 0
        else:
            idx_parent = idx_parent + 1
        # testing if sequence is complete
        # i.e. idx_child = cx_point[0]
        if idx_child == cx_point[0]:
            not_complete = False
    return(child)

In [3]:
rng = np.random.default_rng()

Initialise popsize rows of dim = dim, **with no replacement** in each row

In [11]:
rng.uniform()

0.3878264781416576

In [4]:
popsize = 10
dim = 8

In [5]:
a = rng.choice(dim, size=dim, replace=False)
for _ in range(popsize-1):
    a = np.concatenate((a,rng.choice(dim, size=dim, replace=False)), axis=0)

In [6]:
a = a.reshape(-1, dim)

In [7]:
a

array([[0, 7, 5, 4, 3, 2, 6, 1],
       [7, 6, 1, 2, 3, 0, 5, 4],
       [5, 4, 1, 6, 0, 2, 7, 3],
       [1, 5, 4, 3, 2, 7, 6, 0],
       [6, 1, 7, 2, 0, 5, 3, 4],
       [1, 6, 7, 3, 2, 5, 0, 4],
       [6, 4, 7, 2, 5, 3, 0, 1],
       [3, 6, 7, 2, 4, 0, 5, 1],
       [4, 2, 0, 5, 6, 7, 3, 1],
       [1, 0, 4, 6, 5, 3, 2, 7]], dtype=int64)

In [8]:
b = np.array([1,1,0,4,4,8])

In [9]:
a[b]

array([[7, 6, 1, 2, 3, 0, 5, 4],
       [7, 6, 1, 2, 3, 0, 5, 4],
       [0, 7, 5, 4, 3, 2, 6, 1],
       [6, 1, 7, 2, 0, 5, 3, 4],
       [6, 1, 7, 2, 0, 5, 3, 4],
       [4, 2, 0, 5, 6, 7, 3, 1]], dtype=int64)

## Swap Mutation (inplace)

In [35]:
dim = a.shape[1]
for i in range(a.shape[0]):
    idxs = rng.choice(dim, size=2, replace=False)
    temp = a[i][idxs[0]]
    a[i][idxs[0]] = a[i][idxs[1]]
    a[i][idxs[1]] = temp

## Inversion Mutation (inplace)

In [146]:
max_width = 3
dim = a.shape[1]
for i in range(a.shape[0]):
    invalid_sequence = True
    
    # By ordering, we somehow prevent inversion happening
    # on the bounds, i.e. inversion on say indexes
    # 8.9.0.1 -> 1.0.9.8 will never happen
    # Effect is unknown. In theory will be better to allow
    # also these types of inversion.
    while invalid_sequence:
        sequence = np.sort(rng.choice(dim, size=2, replace=False))
        if ((sequence[1] - sequence[0]) <= max_width) and \
           ((sequence[1] - sequence[0]) > 1):
            invalid_sequence = False
    #sequence = np.arange(sequence[0], sequence[1])
    #a[i][sequence] = a[i][sequence][::-1]
    a[i][sequence[0]:sequence[1]] = a[i][sequence[0]:sequence[1]][::-1]

## Scramble Mutation (inplace)

In [160]:
max_width = 3
dim = a.shape[1]
for i in range(a.shape[0]):
    invalid_sequence = True
    
    # By ordering, we somehow prevent inversion happening
    # on the bounds, i.e. inversion on say indexes
    # 8.9.0.1 -> 1.0.9.8 will never happen
    # Effect is unknown. In theory will be better to allow
    # also these types of inversion.
    while invalid_sequence:
        sequence = np.sort(rng.choice(dim, size=2, replace=False))
        if ((sequence[1] - sequence[0]) <= max_width) and \
           ((sequence[1] - sequence[0]) > 1):
            invalid_sequence = False
    print(sequence)
    rng.shuffle(a[i][sequence[0]:sequence[1]])

[3 5]
[1 4]
[3 5]
[4 6]
[5 7]
[4 6]
[4 7]
[5 7]
[4 6]
[4 7]


In [168]:
a

array([[7, 5, 2, 1, 4, 0, 3, 6],
       [1, 6, 0, 3, 4, 7, 2, 5],
       [4, 2, 1, 7, 5, 3, 6, 0],
       [0, 5, 4, 1, 7, 3, 6, 2],
       [1, 3, 0, 7, 4, 5, 2, 6],
       [5, 1, 2, 4, 6, 3, 0, 7],
       [4, 6, 7, 3, 5, 1, 2, 0],
       [0, 3, 2, 1, 6, 5, 4, 7],
       [5, 0, 1, 7, 6, 3, 2, 4],
       [4, 0, 1, 2, 6, 7, 3, 5]], dtype=int64)

In [170]:
rng.permutation(a[0][1:3])

array([5, 2], dtype=int64)

In [13]:
d = {"parm1": 1, "parm2": 0.6}
d

{'parm1': 1, 'parm2': 0.6}

In [18]:
if not e:
    print("not d")

NameError: name 'e' is not defined

In [31]:
class testclass:
    def __init__(self, a, b, c):
        if not a:
            self.a = 0
        else:
            self.a = "a"
        if not b:
            self.b = {"d": 1, "e": 2}
        elif "d" not in b:
            self.b = {"d": 1}
        self.c = 3
    def callme(self):
        print(self.a, self.b, self.c)

In [35]:
t = testclass(1,{"a": 4},3)

In [36]:
t.callme()

a {'d': 1} 3


In [16]:
if "parm31" not in d:
    print("not")
else:
    print("is")

not


In [252]:
parent1 = a[4]
parent2 = a[8]

In [253]:
crossover_points = np.sort(rng.choice(dim, size=2, replace=False))
crossover_points

array([2, 6], dtype=int64)

In [254]:
crossover_range = np.arange(crossover_points[0], crossover_points[1])
crossover_range

array([2, 3, 4, 5], dtype=int64)

In [255]:
child1 = -1*np.ones(dim, dtype=int)
child2 = -1*np.ones(dim, dtype=int)

In [256]:
child1[crossover_range] = parent2[crossover_range]
child2[crossover_range] = parent1[crossover_range]
child1, child2

(array([-1, -1,  7,  4,  3,  2, -1, -1]),
 array([-1, -1,  5,  4,  1,  3, -1, -1]))

In [257]:
c = complete_sequence(child1, parent1, crossover_points, dim)
c, child1

(array([5, 1, 7, 4, 3, 2, 6, 0]), array([5, 1, 7, 4, 3, 2, 6, 0]))

In [258]:
parent1

array([7, 2, 5, 4, 1, 3, 6, 0], dtype=int64)

In [259]:
c = complete_sequence(child2, parent2, crossover_points, dim)
c, child2

(array([7, 2, 5, 4, 1, 3, 0, 6]), array([7, 2, 5, 4, 1, 3, 0, 6]))

In [260]:
parent2

array([6, 5, 7, 4, 3, 2, 1, 0], dtype=int64)

In [261]:
if offsprings is None:
    offsprings = child1
    offsprings = np.concatenate((offsprings,child2), axis=0)
else:
    offsprings = np.concatenate((offsprings,child1), axis=0)
    offsprings = np.concatenate((offsprings,child2), axis=0)

In [262]:
offsprings.reshape(-1,dim)

array([[7, 5, 3, 2, 6, 4, 1, 0],
       [1, 7, 0, 6, 2, 4, 5, 3],
       [4, 2, 5, 1, 0, 7, 3, 6],
       [5, 6, 4, 1, 3, 0, 7, 2],
       [5, 1, 7, 4, 3, 2, 6, 0],
       [7, 2, 5, 4, 1, 3, 0, 6]])

In [264]:
i = 0
while i <= 10:
    print(i)
    i = i + 1

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
def ordered_crossover(parent1, parent2):
    rng = np.random.default_rng()
    # select two cross-over points
    # Making sure we don't have twice the same index (replace=False)
    crossover_points = np.sort(rng.choice(dim, size=2, replace=False))
    crossover_range = np.arange(crossover_points[0], crossover_points[1])
    #initialise child1,2 array
    child1 = child2 = -1*np.ones(10)
    #keep crossover genes sequence for child1,2
    child1_sequence = parent2[crossover_range]
    child2_sequence = parent1[crossover_range]
    #mutate child1,2
    child1[crossover_range] = parent2[crossover_range]
    child2[crossover_range] = parent1[crossover_range]
    #complete gene sequences
    
    
    
    

(array([1, 6, 2]), array([11, 14,  7]))

(array([-1,  1,  6,  2, -1, -1, -1, -1]),
 array([-1, 11, 14,  7, -1, -1, -1, -1]))

In [121]:
c

array([ 7,  1,  6,  2, 19, 11,  5, 14])

In [123]:
child1, parent1

(array([ 7,  1,  6,  2, 19, 11,  5, 14]),
 array([11, 11, 14,  7, 19,  1, 11,  5]))

In [ ]:
#complete child1 sequence, starting by the upper range
idx_child1 = crossover_points[1]
# we loop for the whole remaining sequence of parent1
# i.e. dim - crossover_range.shape[0]
for idx in range(dim - crossover_range.shape[0]):
    # child1 (using parent1)
    if parent1[idx] not in child1:
        child1[idx_child1] = parent1[idx]
        idx_child1 = idx_child1 + 1
    # child2 (using parent2)
    if parent2[idx] not in child2:
        child2[idx_child2] = parent2[idx]
        idx_child2 = idx_child2 + 1

In [111]:
idx_child1 = crossover_points[1]
for i in range(dim - crossover_range.shape[0]):
    print(idx_child1)
    if idx_child1 == (dim - 1):
        idx_child1 = 0
    else:
        idx_child1 = idx_child1 + 1
    print(i, idx_child1)

4
0 5
5
1 6
6
2 7
7
3 0
0
4 1


In [109]:
crossover_range[1]

2

In [98]:
#complete upper range of the sequence
idx_child1 = idx_child2 = crossover_points[1]
for idx in range(crossover_points[1], dim):
    # child1 (using parent1)
    if parent1[idx] not in child1:
        child1[idx_child1] = parent1[idx]
        idx_child1 = idx_child1 + 1
    # child2 (using parent2)
    if parent2[idx] not in child2:
        child2[idx_child2] = parent2[idx]
        idx_child2 = idx_child2 +1

In [99]:
child1, child2

(array([-1,  1,  6,  2, 19, 11,  5, -1]),
 array([-1, 11, 14,  7,  3, 19,  2, -1]))

In [88]:
parent1, parent2

(array([11, 11, 14,  7, 19,  1, 11,  5]),
 array([15,  1,  6,  2,  3, 19, 19,  2]))

In [ ]:
#move to the lower range of the sequence
#we start where we left of

In [79]:
if 3 not in child1:
    print("not in")

not in


In [48]:
rng = np.random.default_rng()

In [53]:
numbers = rng.choice(dim, size=2, replace=False)
numbers

array([5, 6], dtype=int64)

In [14]:
b = a[np.array([1,4,2])]

In [64]:
c1 = c2 = -1*np.ones(10)
c1, c2

(array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.]),
 array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.]))

In [34]:
# select two points cross-over
crossover_points = np.sort(np.random.randint(0, dim, 2))
crossover_points

array([0, 4])

In [40]:
b[1][crossover_range]

array([12,  9, 16,  3])

In [36]:
b[1]

array([12,  9, 16,  3, 19, 19, 14, 10])

In [39]:
crossover_range = np.arange(crossover_points[0], crossover_points[1])

In [5]:
def sphere(x):
    f = np.square(x).sum(axis=1)
    return(f)

In [42]:
bob = [-1] * dim

In [44]:
type(bob)

list

In [6]:
popfit = sphere(a)
popfit

array([107.07088555, 172.27629801,  86.22860948, 142.93427804,
        49.78607642,  57.42698245,  80.13234532,  99.12066527,
        16.16288705,  11.13031366])

In [15]:
sphere(np.array([ 1.89629502,  5.08390604, -8.81072359]).reshape(-1,3))

array([107.07088561])

In [12]:
idx=np.argsort(popfit)

In [13]:
idx

array([7, 6, 4, 1, 2, 5, 8, 0, 9, 3], dtype=int64)

In [16]:
i = np.arange(popfit.shape[0])
popfit[i]

array([107.07088555, 172.27629801,  86.22860948, 142.93427804,
        49.78607642,  57.42698245,  80.13234532,  99.12066527,
        16.16288705,  11.13031366])

In [30]:
popfit.shape

(10,)

In [8]:
a[idx]

array([[-0.82074236, -1.72802379,  2.714328  ],
       [ 3.9611284 ,  3.99646038, -0.39014557],
       [ 0.49045751,  4.53523272,  4.90934566],
       [ 2.3119507 , -2.46385816, -7.34368174],
       [-8.18451093,  2.16308188, -4.12799727],
       [-2.78479585, -1.36564757, -9.85041017],
       [ 6.79164955, -3.03612509,  8.86967751],
       [ 4.22407366, -7.53049386, -8.8076379 ],
       [ 9.84860135,  3.51130775,  9.99336009],
       [ 5.35993233,  9.98878386,  9.59084163]])

In [18]:
a[i]

array([[ 4.22407366, -7.53049386, -8.8076379 ],
       [ 2.3119507 , -2.46385816, -7.34368174],
       [-8.18451093,  2.16308188, -4.12799727],
       [ 5.35993233,  9.98878386,  9.59084163],
       [ 0.49045751,  4.53523272,  4.90934566],
       [-2.78479585, -1.36564757, -9.85041017],
       [ 3.9611284 ,  3.99646038, -0.39014557],
       [-0.82074236, -1.72802379,  2.714328  ],
       [ 6.79164955, -3.03612509,  8.86967751],
       [ 9.84860135,  3.51130775,  9.99336009]])

In [25]:
k = 3
# Select 3 individuals (index)
idx = np.random.choice(range(a.shape[0]), size=3, replace=False)
print("idx: {}".format(idx))

#get best fitness of the 
#by argsort
best_idx = idx[np.argsort(popfit[idx])[0]]
print("best idx: {}".format(best_idx))
print(a[best_idx])

idx: [1 4 2]
best idx: 4
[-3.69104509 -0.73212688  5.96877314]


In [29]:
idx

array([1, 4, 2])

In [26]:
popfit

array([107.07088555, 172.27629801,  86.22860948, 142.93427804,
        49.78607642,  57.42698245,  80.13234532,  99.12066527,
        16.16288705,  11.13031366])

In [27]:
popfit[idx]

array([172.27629801,  49.78607642,  86.22860948])

In [28]:
np.argsort(popfit[idx])

array([1, 2, 0], dtype=int64)

In [18]:
s = np.random.choice(range(a.shape[0]), size=3, replace=False)
s

array([0, 5, 1])

In [19]:
fitness_selected = popfit[s]

In [20]:
fitness_selected

array([107.07088555,  57.42698245, 172.27629801])

In [21]:
np.argsort(fitness_selected)

array([1, 0, 2], dtype=int64)

In [22]:
np.argsort(np.array([-1,4,90,-7,9.77,9.7,9.776,-7.1]))

array([7, 3, 0, 1, 5, 4, 6, 2], dtype=int64)

In [ ]:
idx_best = 

In [33]:
for _ in range(3):
    print("h")

h
h
h


In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
i = np.array([0,1,1,1,9])

In [35]:
a[i]

array([[ 1.89629502,  5.08390604, -8.81072359],
       [ 3.77908259, -8.27577257, -9.46078333],
       [ 3.77908259, -8.27577257, -9.46078333],
       [ 3.77908259, -8.27577257, -9.46078333],
       [-1.57331226, -2.54421345, -1.4771527 ]])